### ISSUE TITLE
Removing User from a Wobble should not trigger the New-Notification

### ISSUE THREAD

**Issue by Uepsilon** [zeisss/wobble#130]
When removing Users from a Wobble - independent of who removed them, whether it was the user himself or another user - the "new"-counter should not be increased. 

This should be done to prevent Wobbles from popping out of the archive when someone is removed as there is no really new stuff going on. 

Deleting Replies does not trigger this mechanism either, should be lined up.

**Comment by zeisss** [comment]
Closed due to inactivity.
